version: "3.5"
services:
  mongo:
    image: "mongo:latest"
    command: mongod
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
